# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{party_resource}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tristan Harris", "Steve Tooke"]
  s.date = %q{2010-05-25}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{dev+party_resource@edendevelopment.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "lib/party_resource.rb",
     "lib/party_resource/buildable.rb",
     "lib/party_resource/connector.rb",
     "lib/party_resource/connector/base.rb",
     "lib/party_resource/exceptions.rb",
     "lib/party_resource/method_define.rb",
     "lib/party_resource/party_resource.rb",
     "lib/party_resource/property.rb",
     "lib/party_resource/request.rb",
     "lib/party_resource/route.rb"
  ]
  s.homepage = %q{http://github.com/edendevelopment/party_resource.git}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/fixtures/other_class.rb",
     "spec/fixtures/test_base_class.rb",
     "spec/fixtures/test_class.rb",
     "spec/integration/integration_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/connector/base_spec.rb",
     "spec/unit/connector_spec.rb",
     "spec/unit/exceptions_spec.rb",
     "spec/unit/party_resource_spec.rb",
     "spec/unit/request_spec.rb",
     "spec/unit/route_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
  end
end

